export const environment = {
  GRAPHQL_URI: "https://et-ci-dev-abpa-api.azurewebsites.net/",
  GRAPHQL_WS_URI: "wss://et-ci-dev-abpa-api.azurewebsites.net/",
  REDIRECT_URI: "http://localhost:4200/",
  CLIENT_ID: "1At9BpRB5hs4Y8UX2BMecvA97iXoTch8",
  CLIENT_SECRET: "ld-exHhhvAM5EcZZfdU6XZ8v1o4gSJTro4OS8qKsu3FGAQh8xsaA89F82P2VqWSf",
  CLIENT_AUTHORITY: "dev-maiuwd8omanoybhb.us.auth0.com",
  AUTH_TYPE: "auth0",
  NODE_ENV: "production",
  AUTOSAVE_DEBOUNCE_MS: 1200,
  SEARCH_DEBOUNCE_MS: 800,
  MIN_SEARCH_LENGTH: 3,
  MJ_CORE_SCHEMA_NAME: "__mj",
  production: false,
  APPLICATION_NAME: "CDP",
  APPLICATION_INSTANCE: "DEV",
  AUTH0_DOMAIN: "dev-maiuwd8omanoybhb.us.auth0.com",
  AUTH0_CLIENT_SECRET: "e_gvCCV3MqtzEdu9KDKqfSrYId0cJbHEdxI7YGLVvgdKAvyus6OU0DYzYmR7IMfA",
  AUTH0_CLIENTID: "1At9BpRB5hs4Y8UX2BMecvA97iXoTch8",
  TOKEN_CACHE_KEY: 'mj_auth0_token',
  SAS_TOKEN:'sp=racwdli&st=2025-03-26T10:11:06Z&se=2026-03-26T18:11:06Z&spr=https&sv=2024-11-04&sr=c&sig=rrTMPIluGKbBsE1uBydFXSujZt2vWMIVUqpV%2BbODZJI%3D',
  STORAGE_ACCT:'etcidevabpastorage',
  CONTAINER:'abstract-uploads',
}