export const environment = {
    GRAPHQL_URI: "http://localhost:4000/",
    GRAPHQL_WS_URI: "ws://localhost:4000/",
    REDIRECT_URI: "http://localhost:4200/",
    CLIENT_ID: "xR2j07ptogEkO5L6x4Z8seuWeTsglksJ",
    CLIENT_SECRET: "ld-exHhhvAM5EcZZfdU6XZ8v1o4gSJTro4OS8qKsu3FGAQh8xsaA89F82P2VqWSf",
    CLIENT_AUTHORITY: "dev-maiuwd8omanoybhb.us.auth0.com",
    AUTH_TYPE: "auth0",
    NODE_ENV: "development",
    AUTOSAVE_DEBOUNCE_MS: 1200,
    SEARCH_DEBOUNCE_MS: 800,
    MIN_SEARCH_LENGTH: 3,
    MJ_CORE_SCHEMA_NAME: "__mj",
    production: false,
    APPLICATION_NAME: "CDP",
    APPLICATION_INSTANCE: "DEV",
    AUTH0_DOMAIN: "dev-maiuwd8omanoybhb.us.auth0.com",
    AUTH0_CLIENT_SECRET: "e_gvCCV3MqtzEdu9KDKqfSrYId0cJbHEdxI7YGLVvgdKAvyus6OU0DYzYmR7IMfA",
    AUTH0_CLIENTID: "1At9BpRB5hs4Y8UX2BMecvA97iXoTch8",
    TOKEN_CACHE_KEY: 'mj_auth0_token',
}